export const INITIAL_STOCK_PRICE = 100.00;
export const MAX_QUESTIONS = 8;

export const NEWS_TICKER_HEADLINES = [
  "MARKETS RALLY AS TECH SECTOR BOOMS",
  "BREAKING: LIVE INTERVIEW IN PROGRESS",
  "INVESTORS WATCHING CLOSELY",
  "RUMORS OF ACQUISITION SWIRL",
  "CONSUMER CONFIDENCE HITS 5-YEAR HIGH",
  "BREAKING NEWS: SCANDAL IN THE MAKING?",
  "LOCAL CAT SAVED FROM TREE BY FIREFIGHTERS",
  "WEATHER: SUNNY SPELLS WITH CHANCE OF MARKET CRASH",
];

export const JOURNALIST_NAME = "Diane Sawyer-bot";
export const SHOW_NAME = "THE HOT SEAT";
